export 'album.dart';
export 'details.dart';
export 'event_details.dart';
export 'events.dart';
export 'explore.dart';
export 'favourites.dart';
export 'home.dart';
export 'wishes.dart';
export 'video.dart';